### ISSUE TITLE
[Planning] Refactor CI system to support kubeadm for bootstrapping K8s clusters on Packet

### ISSUE THREAD

**Issue by lixuna** [crosscloudci/crosscloudci#100]
Feature: Use kubeadm for bootstrapping K8s clusters on Packet
---

## Short Description: 
- Use kubeadm for bootstrapping K8s clusters on Packet
- 

## Tasks: 

- [x] Plan using kubeadm

**Comment by denverwilliams** [comment]
Investigate if Kubeadm supports Head/RC/Stable releases.
---
Going off the documentation it look like kubeadm supports deploying the k8s from http://gcr.io/kubernetes-ci-images which has images for every commit on head. So we should be able to reference this to support HEAD deployments of K8s.
https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-init/#custom-images

**Comment by lixuna** [comment]
deferring kubeadm to v2.2.0, prioritizing adding arm support #122

**Comment by vielmetti** [comment]
If you run into any particular @packethost related issues on this, please flag me for attention, thanks!

**Comment by lixuna** [comment]
Changing this EPIC to a planning ticket. Closing as "planning complete"

**Comment by lixuna** [comment]
Kubespray implemented in v3.0.0 release on Fri, Oct 18, 2019 

- https://github.com/crosscloudci/crosscloudci/wiki/CNCF-CI-v3.0.0-Release-Notes
