### ISSUE TITLE
[v2.1.0] Implement K8s release selector dropdown (show Stable & Head)

### ISSUE THREAD

**Issue by lixuna** [crosscloudci/crosscloudci#114]
**Feature Name:** 

- Kubernetes release selector dropdown in "Test Environment" section

**Short Description:** 

- add a dropdown to select between Stable and head release of Kubernetes

**Location/URL:** 

- http://x.cncf.ci

**Design Mocks:** 

Desktop: 

![web 960 test-environment-grad-incub-linux state 2 3](https://user-images.githubusercontent.com/26259410/53967847-9a1a7d00-40bb-11e9-973d-f17c71f0ea89.png)

![web 960 test-environment-grad-incub-linux state 2](https://user-images.githubusercontent.com/26259410/53967750-663f5780-40bb-11e9-8baa-83eb7218b4f4.png)

![web 960 test-environment-grad-incub-linux state 1](https://user-images.githubusercontent.com/26259410/53548302-c7cd5800-3af6-11e9-94bf-5a4c6a664281.png)

![web 960 test-environment-grad-incub-linux state 2 1](https://user-images.githubusercontent.com/26259410/53967766-6c353880-40bb-11e9-820b-69d6bdf6e0ec.png)

![web 960 test-environment-grad-incub-linux state 2 2](https://user-images.githubusercontent.com/26259410/53548304-c7cd5800-3af6-11e9-827e-1cc02d6fb92b.png)

Mobile: 

![android mobile accep -- main 5](https://user-images.githubusercontent.com/26259410/53574506-64aee600-3b35-11e9-83bb-73e316ee5717.png)

![android mobile accep -- main 6](https://user-images.githubusercontent.com/26259410/53574048-6926cf00-3b34-11e9-9ce1-c102d7d4405d.png)

![android mobile accep -- main 3](https://user-images.githubusercontent.com/26259410/53574050-6926cf00-3b34-11e9-9d6c-074dff0fc3da.png)

![android mobile accep -- main 4](https://user-images.githubusercontent.com/26259410/53574051-6926cf00-3b34-11e9-8a5b-1fb357dbe0ef.png)

Mobile (expanded section): 

![android mobile accep -- proj expanded stable 4](https://user-images.githubusercontent.com/26259410/53605103-1a048c80-3b7c-11e9-9082-97f661916b81.png)

![android mobile accep -- proj expanded stable 3](https://user-images.githubusercontent.com/26259410/53604970-a498bc00-3b7b-11e9-8837-07a1b6ddd54e.png)

---

Acceptance Criteria
---

On mobile: 

Actions on mobile: 
1.    go to x.cncf.ci on mobile
1.    I should see the selected Test Environment as Kubernetes Stable v1.13.0 (no change)
1.    I should see project deployment status for the selected Test Environment as Kubernetes Stable v1.13.0 (no change, as implemented in #126 )
1.    I should see a down arrow in Test Environment
1.    I can click on the [Kubernetes Stable v1.13.0] button
1.   I can see the "Select K8s environment" modal (uses material.io list element)
1.   I can see a check mark next to the Selected option: ie. Stable v1.13.0 
1.    I can click on the Available option: ie. Head 1234abc
1.    I can see a gray highlight on the clicked Available option: ie. Head 1234abc
1.   the modal closes after making new selection
1.    I can see Head 1234abc in Test Environment on cncf.ci
1.   I can see the status of project deployments to the Kubernetes Head 123abc Test Environment

Project actions: 

Kubernetes in Test Environment:
1. Kubernetes Head release should provision to Packet
  1.  URL should go to a https://gitlab.cncf.ci/cncf/cross-cloud job 

CoreDNS:

1.  CoreDNS Stable release should deploy on Kubernetes Head 1234abc
  1.  URL should go to cross-project job on Kubernetes Head 1234abc
1.  CoreDNS head release should deploy on Kubernetes Head 1234abc
  1.  URL should go to cross-project job on Kubernetes Head 1234abc

Envoy:

1.   Envoy Stable release should deploy on Kubernetes Head 1234abc
1.   URL should go to cross-project job on Kubernetes Head 1234abc
1.   Envoy head release should deploy on Kubernetes Head 1234abc
1.   URL should go to cross-project job on Kubernetes Head 1234abc

Prometheus:

1.   Prometheus Stable release should deploy on Kubernetes Head 1234abc
1.   URL should go to cross-project job on Kubernetes Head 1234abc
1.   Prometheus head release should deploy on Kubernetes Head 1234abc
1.   URL should go to cross-project job on Kubernetes Head 1234abc

Fluentd:

1.   Fluentd Stable release should deploy on Kubernetes Head 1234abc
1.   URL should go to cross-project job on Kubernetes Head 1234abc
1.   Fluentd head release should deploy on Kubernetes Head 1234abc
1.   URL should go to cross-projectob on Kubernetes Head 1234abc

Linkerd:

1.   Linkerd Stable release should deploy on Kubernetes Head 1234abc
1.   URL should go to cross-project job on Kubernetes Head 1234abc
1.   Linkerd head release should deploy on Kubernetes Head 1234abc
1.   URL should go to cross-project job on Kubernetes Head 1234abc

ONAP:

1.   ONAP Stable release should deploy on Kubernetes Head 1234abc
1.   URL should go to cross-project job on Kubernetes Head 1234abc
1.   ONAP head release should deploy on Kubernetes Head 1234abc
1.   URL should go to cross-project job on Kubernetes Head 1234abc

Cancel Action in mobile modal: 
1.   I can see the "Select K8s environment" modal
1.   I can see a check mark next to the Selected option: ie. Stable v1.13.0 
1.   I can press CANCEL to close the modal 
1.   CANCEL button is same Blue color as "CNCF" in footer
1.   I can press outside of the modal to close the modal

1.   Styling matches the mocks

1.   I can see the status of project deployments to the Kubernetes Head 123abc Test Environment

On desktop,
1.    go to x.cncf.ci on mobile
1.    I can see the selected Test Environment as Kubernetes Stable v1.13.0 (no change)
1.   I can see the status of project deployments to the the selected Test Environment as Kubernetes Stable v1.13.0 (no change, as implemented in #126 )
1.    I can see a down arrow in Test Environment
1.    I can click on the [Kubernetes Stable v1.13.0] button
1.   I can see the dropdown
1.   I can see an up arrow in place of the previous down arrow
1.   I can see the Selected option in 1st position / at the top of the menu
1.   I can click on the Available option [Kubernetes Head 1234abc] in 2nd position
1.    I can click on the Available option: ie. Head 1234abc
1.   I can see a gray highlight on the clicked Available option: ie. Head 1234abc
1.   the dropdown closes after making new selection
1.   I can see Kubernetes Head 1234abc in Test Environment on cncf.ci
1.   I can see a down arrow in Test Environment

1.   I can see the status of project deployments to the Kubernetes Head 123abc Test Environment

Project actions: 
CoreDNS:

1.  CoreDNS Stable release should deploy on Kubernetes Head 1234abc
  1.  URL should go to cross-project job on Kubernetes Head 1234abc
1.  CoreDNS head release should deploy on Kubernetes Head 1234abc
  1.  URL should go to cross-project job on Kubernetes Head 1234abc

Envoy:

1.   Envoy Stable release should deploy on Kubernetes Head 1234abc
1.   URL should go to cross-project job on Kubernetes Head 1234abc
1.   Envoy head release should deploy on Kubernetes Head 1234abc
1.   URL should go to cross-project job on Kubernetes Head 1234abc

Prometheus:

1.   Prometheus Stable release should deploy on Kubernetes Head 1234abc
1.   URL should go to cross-project job on Kubernetes Head 1234abc
1.   Prometheus head release should deploy on Kubernetes Head 1234abc
1.   URL should go to cross-project job on Kubernetes Head 1234abc

Fluentd:

1.   Fluentd Stable release should deploy on Kubernetes Head 1234abc
1.   URL should go to cross-project job on Kubernetes Head 1234abc
1.   Fluentd head release should deploy on Kubernetes Head 1234abc
1.   URL should go to cross-projectob on Kubernetes Head 1234abc

Linkerd:

1.   Linkerd Stable release should deploy on Kubernetes Head 1234abc
1.   URL should go to cross-project job on Kubernetes Head 1234abc
1.   Linkerd head release should deploy on Kubernetes Head 1234abc
1.   URL should go to cross-project job on Kubernetes Head 1234abc

ONAP:

1.   ONAP Stable release should deploy on Kubernetes Head 1234abc
1.   URL should go to cross-project job on Kubernetes Head 1234abc
1.   ONAP head release should deploy on Kubernetes Head 1234abc
1.   URL should go to cross-project job on Kubernetes Head 1234abc

Switch back to Kubernetes Stable v1.13.0:
1.    I can click on the [Kubernetes Head 1234abc] button
1.   I can see the dropdown
1.    I can click on the Available option: ie. Stable v1.13.0
1.   I can see a gray highlight on the clicked Available option: ie. Stable v1.13.0
1.   the dropdown closes after making new selection
1.   I can see Kubernetes Stable v1.13.0 in Test Environment on cncf.ci
1.   I can see the status of project deployments to the the selected Test Environment as Kubernetes Stable v1.13.0

Cancel Action in desktop dropdown
1.   I can see the dropdown
1.   I can press the Selected option to close the dropdown (and not change the branch)
1.   I can press outside of the dropdown to close the dropdown

---

_Copied from original issue: vulk/cncf_ci#29_

**Comment by taylor** [comment]
https://github.com/crosscloudci/gitlab-dashboard-updater/issues/1
