### ISSUE TITLE
[v2.1.0] Add Arm support to Kubernetes (stable and head) test environment

### ISSUE THREAD

**Issue by lixuna** [crosscloudci/crosscloudci#126]
_From @lixuna on March 5, 2019 18:47_

**Feature Name:** 

- Add Arm support to Kubernetes (stable and head)

**Short Description:** 

- Add Arm support to Kubernetes (stable and head)
- Add option to select arm options in test environment dropdown  

**Design Mocks:**  
- building on #114 - adding 2 more options to the Test Environment dropdown

DESKTOP: 

Step 1 - "Default Test Environment" = "Kubernetes Stable"
![Web 960 – test-environment Arm - 1](https://user-images.githubusercontent.com/26259410/54367485-710c6600-4640-11e9-9f72-ba8c7acb4fff.png)

Step 2 - In Test Environment Dropdown, the  Selected test environment is shown in "Label"+ with checkmark + bold text
![Web 960 – test-environment Arm - 2](https://user-images.githubusercontent.com/26259410/54373457-44aa1700-464b-11e9-8d68-8a64c02ec435.png)

Step 3 - Hover state over test environment option for "Kubernetes Head Arm"
![Web 960 – test-environment Arm - 2 hover state Head arm](https://user-images.githubusercontent.com/26259410/54373573-7cb15a00-464b-11e9-871c-2dbf77721c86.png)

Step 4 - In Test Environment Dropdown, the  Selected test environment is shown in "Label"+ with checkmark + bold text
![Web 960 – test-environment Arm - 3 head arm selected](https://user-images.githubusercontent.com/26259410/54373627-9a7ebf00-464b-11e9-88e2-f9ae97f818fc.png)

Step 5 - If the selected Test Environment is "Kubernetes Head Arm," dashboard will display status of Build and Deploy stages on "Kubernetes Head Arm" environment
![Web 960 – test-environment Arm - 3 head arm](https://user-images.githubusercontent.com/26259410/54373810-e92c5900-464b-11e9-8e62-b732893d2848.png)

MOCK #1, MOBILE: 

Step 1 -
![Android Mobile – Arm -- MAIN – 1](https://user-images.githubusercontent.com/26259410/54369903-b5016a00-4644-11e9-9616-ac4489e3f024.png)

Step 2 - 
![Android Mobile – Arm -- MAIN – 4](https://user-images.githubusercontent.com/26259410/54369763-7d92bd80-4644-11e9-9d59-3bbfec6880ef.png)

Step 3 -
![Android Mobile – Arm -- MAIN – 3](https://user-images.githubusercontent.com/26259410/54369607-3a384f00-4644-11e9-8d42-e62cd404b6c2.png)

Step 4 - 
![Android Mobile – ACCEP -- MAIN – 3 collapsed sections](https://user-images.githubusercontent.com/26259410/54370414-93ed4900-4645-11e9-9448-19b9beef3900.png)

Step 5 
![Android Mobile – Arm -- Main 3D](https://user-images.githubusercontent.com/26259410/54369608-3a384f00-4644-11e9-9b82-b8565f029c88.png)

** Note: Adding support for Arm to CNCF Project build and deploy stages will be added incrementally in:
- #133   
- #134 
- #135 
- #136 
- #137 

Tasks: 

- [x] Planning
- [x] Design 
- [x] Implementation
   - [x] Updates to K8s configuration 
   - [x] Updates to cross-cloud
   - [x] Updates to trigger client
   - [x] Updates to dashboard updater
   - [x] Updates to frontend
- [x] QA
- [x] Promote to production

---

**Comment by ZhengZhenyu** [comment]
@lixuna Thanks alot for working on this, I noticed that the planning and design tasks are already marked as completed, so is it too late to ask questsions about the design?

Could we make the Arch selection a separate list selector? it will me more obvious for users to see and use, I made a sample graph:

![wanted dashboard](https://user-images.githubusercontent.com/10849016/54404908-e3984700-470f-11e9-8069-218f69bcd778.png)

Thanks alot.

**Comment by lixuna** [comment]
> @lixuna Thanks alot for working on this, I noticed that the planning and design tasks are already marked as completed, so is it too late to ask questsions about the design?
> 
> Could we make the Arch selection a separate list selector? it will me more obvious for users to see and use, I made a sample graph:
> 
> ![wanted dashboard](https://user-images.githubusercontent.com/10849016/54404982-18a49980-4710-11e9-8cb3-ee564066cb61.png)
> 
> Thanks alot.

Thank you @ZhengZhenyu for your feedback. This ticket #126 is currently in progress. Can you please create a new issue with this enhancement request with the sample graph at https://github.com/crosscloudci/ci-dashboard ?

**Comment by ZhengZhenyu** [comment]
@lixuna Thanks for the reply, I will do that
