### ISSUE TITLE
Add Arm support to CNCF Graduated project: Envoy

### ISSUE THREAD

**Issue by lixuna** [crosscloudci/crosscloudci#134]
_From @lixuna on March 14, 2019 15:13_

**Feature Name:** 

- Add Arm support to CNCF Graduated project: Envoy

**Short Description:** 

- Add Arm support to Envoy Stable release
- Add Arm support to Envoy head release

**Audience:** 

- the public, anyone with the URL

**Locale:** 

- en-US

**Device(s) to support:** 

- all screen sizes (phone, tablet, desktop)

**Location/URL:** 

- x.cncf.ci

---
---
Tasks: 
---

_Copied from original issue: vulk/cncf_ci#144_

**Comment by lixuna** [comment]
Status: 
- In progress

What's left: 
- Adding Arm support to Envoy requires upgrading our GitLab instance to support Envoy builds directly on Packet Arm machines (instead of in an emulator). 

ETA:  
- Should be completed by end of next week (post-KubeCon)

**Comment by wavell** [comment]
In order to support the Envoy Arm upgrade, we had to upgrade Gitlab for a new feature (to run jobs conditionally -- arm specific jobs -- based on a variable).  This upgrade caused other issues.  See: https://gitlab.com/gitlab-org/gitlab-ce/issues/37089#note_171212563

**Comment by lixuna** [comment]
Update: Arm support for Envoy build and deploy stages has been added to cncf.ci 
- failed badges will be investigated and new issues will be opened as needed

<img width="927" alt="Screenshot 2019-06-10 09 23 55" src="https://user-images.githubusercontent.com/11701267/59202692-a69eed80-8b62-11e9-83c3-744c61e9d881.png">
