### ISSUE TITLE
Add Arm support to CNCF Graduated project: Fluentd

### ISSUE THREAD

**Issue by lixuna** [crosscloudci/crosscloudci#136]
_From @lixuna on March 14, 2019 15:14_

**Feature Name:** 

- Add Arm support to CNCF Graduated project: Fluentd

**Short Description:** 

- Add Arm support to Fluentd Stable release
- Add Arm support to Fluentd head release

**Audience:** 

- the public, anyone with the URL

**Locale:** 

- en-US

**Device(s) to support:** 

- all screen sizes (phone, tablet, desktop)

**Location/URL:** 

- x.cncf.ci

---
---

Tasks:
---
* [ ]  
* [ ]  

_Copied from original issue: vulk/cncf_ci#145_

**Comment by edsiper** [comment]
Fix: "graduated project"

**Comment by lixuna** [comment]
Arm support has been added to Fluentd and has been promoted to cncf.ci
