### ISSUE TITLE
[ONAP] Prepare onap demos for ONS

### ISSUE THREAD

**Issue by lixuna** [crosscloudci/crosscloudci#14]
**FEATURE** ONAP+CNCF Cross-cloud CI Demos for ONS 2018

1.  20-30 second demo for ONS Opening Keynote
2.  pre-recorded demo for CNCF Booth
3.  live demo plan for CNCF Booth and per request

**Comment by lixuna** [comment]
For 20-30 second demo: 
---

![onap-dashboard-success](https://user-images.githubusercontent.com/11701267/36449717-3e01b776-1651-11e8-9f68-d0d4fdebd6ed.png)


![onap-dashboard-running](https://user-images.githubusercontent.com/11701267/36449722-40cf79b6-1651-11e8-8b11-6b48d17cea89.gif)

**Comment by dankohn** [comment]
+1
