### ISSUE TITLE
[ONAP] Add e2e tests to cross-cloud ci

### ISSUE THREAD

**Issue by lixuna** [crosscloudci/crosscloudci#15]
Good morning, @obriensystems 

We are planning the e2e test portion of the ONAP-SO integration to cross-cloud ci and have a few questions for you. Thanks in advance for your help.

---

**Feature Name:** Add ONAP-SO e2e tests to cross-cloud ci

**Short Description:** 

- integration of functional, ONAP e2e tests to be run by cross-cloud ci system and results displayed on dashboard on the deployment status badges
  - deployment status badges show status of "Cross-project" states: 
    1. app deployment of ONAP on kubernetes 
    1. run e2e tests

**Questions for ONAP:**
1. should e2e tests be containerized?
  - if not containerized, where will they be located and how can we run them?

2. who is building the e2e container?
  - if cross-cloud ci team: what are the e2e tests? how do we run them? 
  - if ONAP is building e2e containers: where is the container located?

3. what are the requirements for running e2e tests?
  - ex. would we need VPN connection to rackspace? see #357 
  - ex. are there any additional ONAP SO containers?

Note: here are the expected results from e2e tests:
  - cross-cloud ci will look for an `exit status=0 for success`
  - cross-cloud ci will consider `non-0 status to be failed`

**Comment by lixuna** [comment]
@obriensystems, thank you for the walk-through of ONAP robot. We will use robot for the ONAP + CNCF CI e2e tests.

**Comment by obriensystems** [comment]
CNCF team,
   Good meeting the other day. Here is the video you requested for your reference of the session.
http://s3.amazonaws.com/onap/cncf_20180223_oom_zoom_0.mp4
   Also some links to get you starting brining up all of OOM deployed ONAP.

Posted to
https://github.com/crosscloudci/crosscloudci/issues/16
and
https://lists.onap.org/pipermail/onap-discuss/2018-February/008010.html
for
https://onsna18.sched.com/speaker/ajoshipura 

OOM
https://wiki.onap.org/display/DW/ONAP+Operations+Manager+Project
https://wiki.onap.org/display/DW/OOM+User+Guide
https://wiki.onap.org/display/DW/OOM+Developer+Guide


root deployment page
https://wiki.onap.org/display/DW/ONAP+on+Kubernetes
Running the rancher RI
https://wiki.onap.org/display/DW/ONAP+on+Kubernetes+on+Rancher
on multiple cloud system VM’s
https://wiki.onap.org/display/DW/ONAP+on+Kubernetes+on+Amazon+EC2
https://wiki.onap.org/display/DW/ONAP+on+Kubernetes+on+Microsoft+Azure

Mikes’ changes for SO (new config) and the older MSO – just went into master
https://gerrit.onap.org/r/#/q/status:merged+oom+standardized-configuration
