### ISSUE TITLE
Separate dropdown list for architecture selection

### ISSUE THREAD

**Issue by ZhengZhenyu** [crosscloudci/crosscloudci#152]
**Feature Name:**

-  Separate dropdown list for architecture selection

**Short Discription:**

Issue https://github.com/crosscloudci/crosscloudci/issues/126 proposed to add 2 more options to the Test environment dropdown to indicating there is ARM support to Kubernetes tests. It could be more clear for users to see the tests and results if we can separate the architecture selection to a new dropdown list. And the rest of the bahaviors stay the same as proposed in https://github.com/crosscloudci/crosscloudci/issues/126.

The dashboard appearence proposed in https://github.com/crosscloudci/crosscloudci/issues/126 is:
![dashboard 126](https://user-images.githubusercontent.com/26259410/54373627-9a7ebf00-464b-11e9-88e2-f9ae97f818fc.png)

The output of the proposed enhancement for dashboard CI is:

![wanted dashboard](https://user-images.githubusercontent.com/10849016/54404982-18a49980-4710-11e9-8cb3-ee564066cb61.png)

**Comment by lixuna** [comment]
To do: update UI to use radio buttons for options, remove dropdowns

**Comment by lixuna** [comment]
Marking this issue as closed. 

Many thanks for the suggestion to make the architecture options more visible for users. This goal was appreciated and implemented in issue #186

- [Enhancement] select Test Environment configuration using radio button controls on cncf.ci [#186](https://github.com/crosscloudci/crosscloudci/issues/186)
