### ISSUE TITLE
Planned outage of cncf.ci during Packet maintenance in SJC1

### ISSUE THREAD

**Issue by lixuna** [crosscloudci/crosscloudci#153]
Planned outage of cncf.ci during Packet maintenance in SJC1
---

## Short description: 
- Planned data center migration in Packet's SJC1 center on Saturday, June 22nd @ 6:00pm PT
   - maintenance window is forecasted to be approximately 10 hours
   - plans to reduce any offline windows to under 4 hours within that period
- Related ticket YOLE-6774-SHMG

Tasks:

- [x]  Coordinated shut down of cncf.ci servers:
   - staging.cncf.ci
   - gitlab.cncf.ci
   - cidev.cncf.ci
   - dev.cncf.ci

- [x]  Coordinated restart of cncf.ci servers:
   - staging.cncf.ci
   - gitlab.cncf.ci
   - cidev.cncf.ci
   - dev.cncf.ci

**Comment by denverwilliams** [comment]
All cncf.ci infra is now back online.
