### ISSUE TITLE
[Software updates] Update Ruby on ONAP ci service https://github.com/crosscloudci/onap-ciservice

### ISSUE THREAD

**Issue by lixuna** [crosscloudci/crosscloudci#164]
**Feature Name:** 

- Update Ruby on ONAP ci service https://github.com/crosscloudci/onap-ciservice

**Short Description:** 

- Update Ruby in https://github.com/crosscloudci/onap-ciservice/blob/master/Dockerfile
- ensure that functionality continues to work as expected

**Comment by lixuna** [comment]
@nupejosh @williscool ONAP Stable build failed on staging.cncf.ci 

Error logs say: 

```
Your Ruby version is 2.6.5, but your Gemfile specified 2.6.3
ERROR: Job failed: exit code 1
```

**Comment by lixuna** [comment]
@watson @williscool @nupejosh What is the status of resolving the error logs?

>>> Your Ruby version is 2.6.5, but your Gemfile specified 2.6.3
ERROR: Job failed: exit code 1

**Comment by wavell** [comment]
@lixuna looks like the builds are back to passing/failing in the manner that they were before the upgrade.  take a look at dev.cncf.ci

**Comment by lixuna** [comment]
https://github.com/crosscloudci/onap-ciservice/pull/7 merged and tested on staging

Build job passed as expected https://gitlab.staging.cncf.ci/onap/so/-/jobs/181154 - no errors in logs

I'll create a PR to promote Ruby version update on ONAP ci service to production
