### ISSUE TITLE
[CI Refactor] Enable new Test Environment provisioning (and disable cross-cloud K8s provisioning)

### ISSUE THREAD

**Issue by lixuna** [crosscloudci/crosscloudci#181]
**Feature Name:** 

- Enable new Test Environment provisioning 
- Disable cross-cloud K8s provisioning

**Short Description:** 

MVP: 
 - k8s-infra only using manually pre-provisioned hardware
 - Static hard coding of hardware pipeline

**Location/URL:** 

- x.cncf.ci

---
---
Planning: 
* [x]  going with MVP option now, update after kubecon

Implementation: 
* [x]  N/A - Global Configuration Tasks
* [x]  Infra-Provisioning Tasks
* [x]  GitLab Configuration CI System Backend Tasks
* [x]  Trigger Client Tasks
* [x]  N/A - Status Repository Tasks
* [x]  N/A - Frontend Plumbing Tasks
* [x]  N/A - Frontend Styling Tasks

QA: 
* [x]  test on cidev
* [x]  test on staging
* [x]  merge to production

**Comment by taylor** [comment]
## PR's required for production promotion

- [x] [cncf-configuration](https://github.com/crosscloudci/cncf-configuration/pulls) (k8s version and helm charts)
   - [x] Created  https://github.com/crosscloudci/cncf-configuration/pull/155
   - [x] Reviewed
   - [x] Merged
- [x] [crosscloudci-trigger](https://github.com/crosscloudci/crosscloudci-trigger/pulls) (k8s infra)
   - [x] Created https://github.com/crosscloudci/crosscloudci-trigger/pull/35
   - [x] Reviewed
   - [x] Merged
- [x] k[ubernetes-configuration](https://github.com/crosscloudci/kubernetes-configuration/pulls) (disabling builds)
   - [x] Created https://github.com/crosscloudci/kubernetes-configuration/pull/12
   - [x] Reviewed
   - [x] Merged
- [x] [cross-project ](https://github.com/crosscloudci/cross-project/pulls)(project updates for k8s infra)
   - [x] Created https://github.com/crosscloudci/cross-project/pull/8
   - [x] Reviewed
   - [x] Merged
- [x] [k8s-infra](https://github.com/crosscloudci/k8s-infra/pulls) (new)
   - [x] Created https://github.com/crosscloudci/k8s-infra/pull/3
   - [x] Reviewed
   - [x] Merged
- [x] [fluentd-configuration](https://github.com/crosscloudci/fluentd-configuration/pulls) (build and app deploy on new k8s)
   - [x] Created https://github.com/crosscloudci/fluentd-configuration/pull/32
   - [x] Reviewed
   - [x] Merged
- [x] [coredns-configuration](https://github.com/crosscloudci/coredns-configuration/pulls) (build and app deploy on new k8s)
   - [x] Created https://github.com/crosscloudci/coredns-configuration/pull/36
   - [x] Reviewed
   - [x] Merged
- [ ] [prometheus-configuration ](https://github.com/crosscloudci/prometheus-configuration/pulls)(build and app deploy on new k8s)
   - [x] Created https://github.com/crosscloudci/prometheus-configuration/pull/35
   - [ ] Reviewed
   - [ ] Merged

**Comment by lixuna** [comment]
New Test Environment provisioning (using kubespray) enable and cross-cloud disabled in v3.0.0 release on Fri, Oct 18, 2019 

- https://github.com/crosscloudci/crosscloudci/wiki/CNCF-CI-v3.0.0-Release-Notes
