### ISSUE TITLE
[Adding new project] Find most recent build in Travis CI build history

### ISSUE THREAD

**Issue by lixuna** [crosscloudci/crosscloudci#192]
**Issue Name:**

- Find most recent build in Travis CI build history

**Short Description:**

- When using pagination (see #189) to go through Travis CI build history the latest build for a commit SHA was not found.
- Sorting by build number (which increments per project) is needed

Tasks:

- [x]   Planning
- [x]   Implementation
    - [x]   CI Proxy Tasks
    - [x]   Travis CI Plugin Tasks
- [x]   QA / Integration

## Acceptance Criteria: tbd

**Comment by taylor** [comment]
This ticket and #189 should be promoted as one set in a PR.

**Comment by lixuna** [comment]
Closing ticket as completed, part of v2.6.0 release to production
