### ISSUE TITLE
arm64 ci failing due to c1.large.arm inventory in NRT1

### ISSUE THREAD

**Issue by lixuna** [crosscloudci/crosscloudci#198]
Re-post from https://github.com/cncf/wg-ci/issues/31 from @vielmetti

Noted by @cayu53 that the Arm builds are current broken, due to inventory issues in NRT1 with c1.large.arm.

**Comment by lixuna** [comment]
Thank you @ed.packet

c2.large.arm v1 looks like a good choice for cncf.ci.

Which region/location would you like us to use for the 3 AM nightly builds?

**Comment by vielmetti** [comment]
Try NRT1 for the first run, thanks @lixuna !

**Comment by lixuna** [comment]
cc @denverwilliams

**Comment by vielmetti** [comment]
We'll watch the 3am builds and plan accordingly, @lixuna !

**Comment by lixuna** [comment]
Thank you @vielmetti 

Both Arm servers provisioned as expected today :) 

K8s Stable+Arm = https://gitlab.cncf.ci/cncf/cross-cloud/-/jobs/176903 ✅ 

K8s Head+Arm = https://gitlab.cncf.ci/cncf/cross-cloud/-/jobs/176911 ✅
