### ISSUE TITLE
[Visual Bug] Test Environment box hides K8s logo on Firefox 70.0.1 on Windows 10 (i7) platform, 100%

### ISSUE THREAD

**Issue by lixuna** [crosscloudci/crosscloudci#211]
**Feature Name:** 

- [Visual Bug] Test Environment box hides K8s logo on (device) (browser)

**Short Description:** 

- Reported via CNCF slack #cncf-ci 
- Followup to https://github.com/crosscloudci/crosscloudci/issues/150
- device type: Windows 10 (i7) platform
- browser type: Firefox 70.0.1 
- view at: 100%

**Comment by cayu53** [comment]
This is with Firefox 70.0.1 on Windows 10 (i7) platform. Zooming 100% or other ratios does not change this. 
See attached JPEG:
![cncf-ci](https://user-images.githubusercontent.com/52464344/68406148-316b2f00-0179-11ea-8590-a3d9233fd93b.jpg)

**Comment by cayu53** [comment]
Argh... somehow my screen capture didn't capture the "test Environment box" - this one does...

![cncf-ci-2](https://user-images.githubusercontent.com/52464344/68406508-dc7be880-0179-11ea-8d74-652b9e170431.jpg)

**Comment by williscool** [comment]
hmm I can't seem to reproduce this

![image](https://user-images.githubusercontent.com/394931/68411854-446e0700-0159-11ea-992a-80183d8e646d.png)


![cncf-ci-dashboard-desktop-test-env-text-11-7-2019](https://user-images.githubusercontent.com/394931/68412709-b2ff9480-015a-11ea-8eb8-7df149353b3e.gif)

im on windows 10 and I can't think of anything operating system / or processor related that would cause this

- are you by chance using a nightly build of FF?
- what is screen size is this screen?
- also try clearing the cache and refreshing

**Comment by williscool** [comment]
@cayu53 ^

**Comment by cayu53** [comment]
Hi @williscool - I cleared my browser cache but no change. I tried with Chrome browser and look is OK with that browser. The screen size I use is 1920 x 1080 (I don't use nightly builds of FF)

**Comment by williscool** [comment]
have finally been able to repo by doing random zooms

![cncf-ci-dashboard-desktop-various-zooms-test-env-text-11-7-2019](https://user-images.githubusercontent.com/394931/68420700-e21e0200-016a-11ea-94c3-a0aef947ac51.gif)

must be some aspect ratio thing. working on a fix

**Comment by cayu53** [comment]
Good, thanks!

**Comment by lixuna** [comment]
Bug fix promoted to production on Tue, Nov 2019, closing issue
