### ISSUE TITLE
[BUG] Fix provisioning failures on cncf.ci 

### ISSUE THREAD

**Issue by lixuna** [crosscloudci/crosscloudci#223]
**Describe the bug**
- all 4 configurations in the Test Environment of cncf.ci have FAILED (K8s Stable+x86, K8s Stable+Arm, K8s Head+x86, K8s Head + Arm)

**To Reproduce**
1. Go to https://cncf.ci/
2. Keep default test environment configuration
3. Click on Failed button
4. View new tab for https://gitlab.cncf.ci/cncf/cross-cloud/-/jobs/236035
5. See error

**Expected behavior**
- All 4 test environment configurations should have PASSED

**Screenshots**

**Test Environment Configuration:**
 - K8s: Stable or Head - both
 - Architecture: x86 or Arm - both

**Project name:**
- CoreDNS, Envoy, etc - N/A

**Column name:**
- Release, Build or Deploy - N/A - Provisioning in Test Environment

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by agentpoyo** [comment]
Seems the error in dev (same error in staging and prod) starting around 2 weeks ago is:

```
$ /k8s-infra/bin/k8sinfra generate_config --arch="$ARCH" --release-type="$PIPELINE_RELEASE_TYPE" --infra-job="$INFRA_PIPELINE" -o /tmp/cluster.yml
/usr/local/lib/ruby/2.6.0/psych.rb:456:in `parse': (<unknown>): mapping values are not allowed in this context at line 8 column 12 (Psych::SyntaxError)
	from /usr/local/lib/ruby/2.6.0/psych.rb:456:in `parse_stream'
	from /usr/local/lib/ruby/2.6.0/psych.rb:390:in `parse'
	from /usr/local/lib/ruby/2.6.0/psych.rb:277:in `load'
	from /k8s-infra/bin/k8sinfra:264:in `get_hosts'
	from /k8s-infra/bin/k8sinfra:221:in `generate_config'
	from /usr/local/bundle/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /usr/local/bundle/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/bundle/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /usr/local/bundle/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /k8s-infra/bin/k8sinfra:345:in `<main>'
```

This might indicate the /tmp/cluster.yml generated config or something in the k8sinfra has an invalid format (missing space, bad character, etc), from the 'parse' error it's throwing.

**Comment by agentpoyo** [comment]
https://gitlab.cncf.ci/cncf/cross-cloud/-/jobs/236810

Stable Provisioning errors are now passing with success.
