### ISSUE TITLE
[BUG] https://cncf.ci/ page shows test failure for a long time

### ISSUE THREAD

**Issue by cpanato** [crosscloudci/crosscloudci#224]
**Describe the bug**
The page https://cncf.ci/ shows a CI Dashboard overview and that is showing a failure status for a long time.
Going deep in the link and checking the pipelines most likely the information that is needed to run the pipeline found [here](https://gitlab.cncf.ci/cncf/cross-cloud/blob/master/.gitlab-ci.yml) was wiped out from the pipeline due to some rules in the gitlab CI to remove old artifacts from the pipeline, the repo is this one https://gitlab.cncf.ci/cncf/infra-provisioning/-/jobs

Maybe just update the config in gitlab and this will be fixed or as soon the job run extract the configuration and add that in the cross-cloud variables to be used by the pipeline

**To Reproduce**
n/a

**Expected behavior**
The pipeline be able to run

**Screenshots**

**Test Environment Configuration:**
 - K8s: Stable or Head
 - Architecture: x86 or Arm

**Project name:**
- CoreDNS, Envoy, etc

**Column name:**
- Release, Build or Deploy

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by lixuna** [comment]
This issue has been resolved in #223
