### ISSUE TITLE
[Enhancement] Reduce complexity of maintenance of cncf.ci by deleting cidev, dev and staging gitlab server resources

### ISSUE THREAD

**Issue by lixuna** [crosscloudci/crosscloudci#233]
[Acceptance Criteria](https://github.com/crosscloudci/crosscloudci/issues/233#issuecomment-767838547)

**Describe the enhancement:**
Delete cidev, dev and staging gitlab server resources

**Business value:**
- Reduce complexity of maintaining cncf.ci
- Reduce steps needed to update stable release versions of cncf projects
- Reduce steps needed to add new projects in the future
- Reduce number of servers in use

**What we have now:**
Gitlab server resources for cidev, dev, staging and production
- https://gitlab.dev.cncf.ci/
- https://gitlab.cidev.cncf.ci/
- https://gitlab.staging.cncf.ci/
- https://gitlab.cncf.ci/

User facing, frontend dashboard for cidev, dev, staging and production
- dev.cncf.ci/
- cidev.cncf.ci/
- staging.cncf.ci/
- cncf.ci/

**What we'd like to have:**
Gitlab server resource for production only
- https://gitlab.cncf.ci/

User facing, frontend dashboard for dev and production
- dev.cncf.ci/
- cncf.ci/

### Implementation tasks:
- [ ] tbd

### Documentation tasks:

- [ ] update [New Release Update Steps](https://github.com/crosscloudci/crosscloudci/wiki/CNCF-CI-Dashboard---New-Release-Update-Steps)

### QA tasks

Dev Review: 
- [ ] walk through A/C
- [ ] do you get the expected result?
- [ ] if yes, 
   - [ ] move to `Needs Peer Review` column  
   - [ ] create Pull Request and follow check list
   - [ ] Assign 1 or more people for peer review
- [ ] if no, document what additional tasks will be needed

Peer review:
- [ ] walk through A/C
- [ ] do you get the expected result?
- [ ] if yes, 
   - [ ] move to `Done` column
   - [ ] Approve pull request
- [ ] if no, 
   - [ ] document what did not go as expected, including error messages and screenshots (if possible)
   - [ ] Add comment to pull request
   - [ ] request changes to pull request

**Comment by lixuna** [comment]
Acceptance Criteria
---


**Project update should go from dev through production across the 2 dashboards with the single gitlab backend**
- [x] Project update noticed (eg. new version)
- [x] Run a manual pipeline to verify the new stable release runs successfully. 
- [x] PR to `master` created
- [x] Review PR
- [x] Merge PR to `master`
- [x] Initiate a test run with the trigger client for the dev environment to cause the change to show on https://dev.cncf.ci/
- [x] Verify that the new stable release successfully runs; document if it fails to diagnose
- [x] Create PR from `master` to `production`
- [x] Check production dashboard https://cncf.ci after the nightly cron job runs 
- [x] The new change should be on the production dashboard

**Documentation for new release steps are current**
- [x] When I go to https://github.com/crosscloudci/crosscloudci/wiki/CNCF-CI-Dashboard---New-Release-Update-Steps
- [x] I should see updated steps for using the 2 dashboard environments for promoting changes to projects to production


**List of released resources**
- [ ] Deleted server resources are listed in this ticket

**Comment by lixuna** [comment]
Level of effort in pts: 5
---

- @lixuna 3
- @denverwilliams 5
- @taylor 5
- @agentpoyo 5

**Comment by agentpoyo** [comment]
List of instances shutdown that will not be needed after ther reduction:

Stable/Head DEV Clusters:
![dev_ci_stable_head_shutdown](https://user-images.githubusercontent.com/14348948/106046033-59f58680-60a7-11eb-8c18-c22381e4b767.png)

Gitlab Runners:
![dev_ci_runners_shutdown](https://user-images.githubusercontent.com/14348948/106046087-6da0ed00-60a7-11eb-9bbc-5394df8f05c9.png)

**Comment by agentpoyo** [comment]
All projects on dashboard have been updated to default to master in their .gitlab-ci.yml configs; all runner settings pointed at master branch.

**Comment by agentpoyo** [comment]
https://github.com/crosscloudci/crosscloudci/wiki/CNCF-CI-Dashboard---New-Release-Update-Steps has been updated with new steps.

**Comment by lixuna** [comment]
Thanks @agentpoyo 

Would it be possible to get a text list of the deleted server names so that the text list can be copied/pasted into an email?

**Comment by agentpoyo** [comment]
@lixuna 

List of servers (shutdown currently, plan to delete):

amd64head-dv-pd-master1
amd64head-dv-pd-worker1
amd64stable-dv-pd-master1
amd64stable-dv-pd-worker1
runner.cidev.cncf.ci
runner.cidev.cncf.ci-arm
runner.dev.cncf.ci
runner.dev.cncf.ci-arm
runner.staging.cncf.ci
runner.staging.cncf.ci-arm
cidev.cncf.ci
dev.cncf.ci
staging.cncf.ci

**Comment by agentpoyo** [comment]
Oh, let me note that the following 3 servers:

cidev.cncf.ci
dev.cncf.ci
staging.cncf.ci

Are all in the CNCF Sandbox project.

While the others are in the Cross-Cloud CI project:

amd64head-dv-pd-master1
amd64head-dv-pd-worker1
amd64stable-dv-pd-master1
amd64stable-dv-pd-worker1
runner.cidev.cncf.ci
runner.cidev.cncf.ci-arm
runner.dev.cncf.ci
runner.dev.cncf.ci-arm
runner.staging.cncf.ci
runner.staging.cncf.ci-arm
