### ISSUE TITLE
Update ONAP integration to support change in container tags for nightly release

### ISSUE THREAD

**Issue by lixuna** [crosscloudci/crosscloudci#40]
Problem: ONAP builds for head release are failing
---

**When did it appear:**
- Wed, Mar 14th
- Release v1.2.0

**What seems to be the cause:** 
- change in container tags for nightly release

**What seems to be the solution:** 
- Update ONAP integration to support change in container tags for nightly release

**Comment by taylor** [comment]
This actually appears to be an upstream failing  build.  It started with build 318, https://jenkins.onap.org/view/Daily-Jobs/job/so-master-docker-version-java-daily/318, and is still failing as of build 325.

A snippet from the Jenkins console logs shows a MSO dependency failure message:

```
09:27:10 [INFO] --- maven-enforcer-plugin:3.0.0-M1:enforce (enforce-no-snapshots) @ common ---
09:27:10 [WARNING] Rule 0: org.apache.maven.plugins.enforcer.RequireReleaseDeps failed with message:
09:27:10 
Found Banned Dependency: org.onap.appc.client:client-lib:jar:1.3.0-SNAPSHOT
09:27:10 Found Banned Dependency: org.onap.aai.aai-common:aai-schema:jar:1.2.1-SNAPSHOT
09:27:10 Found Banned Dependency: org.onap.aai.aai-common:aai-annotations:jar:1.2.1-SNAPSHOT
09:27:10 Use 'mvn dependency:tree' to locate the source of the banned dependencies.
09:27:10 [INFO] ------------------------------------------------------------------------
09:27:10 [INFO] Reactor Summary:
09:27:10 [INFO] 
09:27:10 [INFO] so ................................................. SUCCESS [ 22.048 s]
09:27:10 [INFO] MSO Common classes ................................. FAILURE [ 15.071 s]
```

@obriensystems, is this something you can help with or should we wait until the build start passing again?

**Comment by obriensystems** [comment]
Lucina,
   Hi, I would bring this up with the SO team – the fastest way would be to raise a HIGH JIRA on this or post to the onap-discuss under the heading [SO] with links to your system.

    Examples
https://lists.onap.org/pipermail/onap-discuss/2018-March/
https://jira.onap.org/browse/SO-286 
https://jira.onap.org/browse/SO-290

**Comment by lixuna** [comment]
Upstream ticket: https://jira.onap.org/browse/AAI-946
