### ISSUE TITLE
[03-27-2018] inventory issues causing failed deployments on Packet

### ISSUE THREAD

**Issue by lixuna** [crosscloudci/crosscloudci#42]
https://gitlab.cncf.ci/cncf/cross-cloud/-/jobs/68192

> We have noted some failures of CNCF deployments in our AMS1 data center, due to inventory of the Type 1 server there.
> 
> If it's possible to rehome those tests to EWR1 (New Jersey) there's more inventory available there.
> 
> Thanks!
> Ed

**Comment by lixuna** [comment]
Update: we have relocated CNCF Cross-cloud tests to EWR1 (New Jersey) and are still seeing failed status badges. 

The cross-cloud dashboard refreshes at 3 AM Eastern Time daily. It appears that resources have not been available for our use at that particular time of day.

@ed would it be possible to reserve instances for the CNCF Cross-cloud testing system?

**Comment by lixuna** [comment]
Update: tests have been relocated to EWR1 (New Jersey) location.

**Comment by vielmetti** [comment]
Tests are still failing; it looks like there's a bootstrapping phase that's timing out  too quickly.

See

https://gitlab.cncf.ci/cncf/cross-cloud/-/jobs/77480

and the terraform errors about 30 seconds in:

```
module.master.packet_device.masters.0: Still creating... (30s elapsed)
module.master.packet_device.masters.2: Still creating... (30s elapsed)
module.master.packet_device.masters.1: Still creating... (30s elapsed)
module.worker.packet_device.workers: Still creating... (30s elapsed)

Error: Error applying plan:

4 error(s) occurred:

* module.master.packet_device.masters[2]: 1 error(s) occurred:

* packet_device.masters.2: 
* module.worker.packet_device.workers: 1 error(s) occurred:

* packet_device.workers: 
* module.master.packet_device.masters[0]: 1 error(s) occurred:

* packet_device.masters.0: 
* module.master.packet_device.masters[1]: 1 error(s) occurred:

* packet_device.masters.1: 

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

```

**Comment by vielmetti** [comment]
All tests (except for one that's failing everywhere) are passing today. Hooray!
