### ISSUE TITLE
vsphere: Please set VSPHERE_DESTROY_SKIP to true 

### ISSUE THREAD

**Issue by akutz** [crosscloudci/crosscloudci#74]
Hi,

Please set the option `VSPHERE_DESTROY_SKIP` to `true` for the time being. Due to recent failures, #72 and #73, and others we've seen, it would be useful for the failed environments to stay online so myself and @figo are able to investigate the reasons why deployments are not working as expected.

Thank you.

**Comment by denverwilliams** [comment]
@akutz i have set this on production now, so the next deployment should stay around.

**Comment by akutz** [comment]
Hi @denverwilliams,

Thank you. This does [not appear](https://gitlab.cncf.ci/cncf/cross-cloud/-/jobs/90750) to have worked however. The linked log shows a failed build, but it also shows VMs having been deployed. Except when I check, the VMs and their resource pool have been removed.

**Comment by akutz** [comment]
Hi @denverwilliams,

Please undo this. We are not finding the bandwidth to debug the issues. Have you had any luck?

**Comment by akutz** [comment]
Hi @denverwilliams,

Please, **please** undo this change. It's overwhelming our system. Thank you.

cc @lixuna @taylor @figo @clintkitson

**Comment by akutz** [comment]
Hi @denverwilliams,

Can you please undo this change. Thank you.

**Comment by taylor** [comment]
VSPHERE_DESTROY_SKIP is now set to false
