### ISSUE TITLE
[Google Cloud] exceeded quota causes GCE and GKE deployments to fail

### ISSUE THREAD

**Issue by lixuna** [crosscloudci/crosscloudci#8]
Timeline: 

- 2/6/2018 Cross-cloud team submitted initial request for quota increase to Google Cloud
- 2/6/2018 pre-payment made for quota increase
- 2/7/2018 pending reply from approval team
- 2/8/2018 pending reply from approval team
- 2/9/2018 pending reply, further evaluation needed
- 2/12/2018 pending reply, additional time for evaluation needed
- 2/12/2018 Cross-cloud team requested an expedite of this request, as it impacts cncf.ci
- 2/13/2018 expedite has been shared with approval team

**Comment by dankohn** [comment]
I'm sharing with the GKE product manager, thanks.

--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com

**Comment by lixuna** [comment]
Thank you @dankohn

**Comment by lixuna** [comment]
Google Cloud Support 1:32 AM (6 hours ago) 
The involved teams are now discussing the quota increase request and the result of the review will be posted soon.

I will keep you updated to your request and did follow up to the team to arrive to a decision.

We appreciate your patience for the quota increase request.

**Comment by lixuna** [comment]
Google Cloud Support | Google Cloud Support | 2:22 AM (6 hours ago) |   

We truly appreciate your patience and understanding with your quota increase request. The involved teams are nearing to a decision and hopefully we will get a good news from them tomorrow.

I will do my best to have the quota that you needed as soon as possible.

**Comment by lixuna** [comment]
Google Cloud Support | Google Cloud Support 
Fri, Feb 16, 2018 at 2:48 AM

Good news! Your quota increase request for coastal-emitter-194318 has been approved. I will process your request right away so that this can be enforced as soon as possible.
