### ISSUE TITLE
Integrate OpenStack with Cross-cloud CI and dashboard

### ISSUE THREAD

**Issue by lixuna** [crosscloudci/crosscloudci#9]
Feature: to add an OpenStack column to cncf.ci deployments and integrate OpenStack to the Cross-cloud CI project

Timeline: 
- CNCF CI Cross Cloud Demo with OpenStack on October 3rd, 2017
- Received https://github.com/cncf/cross-cloud/pull/111 on December 6th, 2017
- F2F working session at Kubecon on December 7th, 2017
- Debugging working session on February 13th, 2018

Two issues discussed for debugging:

1. load balancer issues
1. Subnets not deleting issue

Next Steps:
- [ ]  Chris will work with Mohammad on the load balancer issues
- [ ]  Chris might update the Terraform version
- [ ]  Chris will clean up duplicated code
- [ ]  Chris will submit a bug issue for ports not deleting issue

cc @denverwilliams @hogepodge 

Mock of OpenStack on cncf.ci:

![cncf_dashboard-onap_baremetal_openstack](https://user-images.githubusercontent.com/11701267/36172962-1bd12616-10cd-11e8-9ca0-0fddc605361b.png)

**Comment by hogepodge** [comment]
K8s tracking issue. https://github.com/kubernetes/kubernetes/issues/52249

**Comment by hogepodge** [comment]
New PR https://github.com/crosscloudci/cross-cloud/pull/128
